name: Compile report

on:
  push:
    branches: [ master , report ]



jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2







    - name: Install latex and related packages
      run: |
        sudo apt update
        sudo apt install -y texlive-latex-extra texlive-science latexmk curl

    - name: Checkout submodules
      uses: srt32/git-actions@v0.0.3
      with:
        args: git submodule update --init --recursive

    - name: report
      run: |
        make -C doc/report report.pdf

    - name: Upload report
      uses: actions/upload-artifact@v2
      with:
        name: report.pdf
        path: doc/report/report.pdf
